### ISSUE TITLE
What needs doing?

### ISSUE THREAD

**Issue by codesilverback** [AgSync/IdentityServer3.Contrib.Store.Redis#1]
Hi. I'm looking into Redis token stores for IS2.  What makes this not ready for production use and how can I help get it there?

**Comment by kylesonaty** [comment]
Well this effort has kinda been abandoned. it was for IS3 only so I have no idea if it will work for IS2. The reason it was abandoned was because there are a few methods in the `IRefreshTokenStore` and `IAuthorizationCodeStore` that really don't make sense to implement in Redis. They can be done but it would feel more like a hack. If you want to go ahead and try to implement it you can. Check out `GetAllAsync` and `RevokeAsync` in [refresh token store](https://github.com/AgSync/IdentityServer3.Contrib.Store.Redis/blob/master/src/IdentityServer3.Contrib.Store.Redis/RedisRefreshTokenStore.cs#L62) and [authorization code store](https://github.com/AgSync/IdentityServer3.Contrib.Store.Redis/blob/master/src/IdentityServer3.Contrib.Store.Redis/RedisAuthorizationCodeStore.cs#L47)

This does however work if you are only supporting login.

**Comment by codesilverback** [comment]
I misspoke, I meant IS3 (ver 2.3).

**Comment by kylesonaty** [comment]
Since this is abandoned feel free to make a fork and work on it. The direction that I am going in is using a different store. I created [basically the same thing use Azure Table Storage.](https://github.com/kylesonaty/IdentityServer3.Contrib.Store.AzureTableStorage)
